project:
  type: website
  output-dir: docs


website:
  title: "rwd-mls-players"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01-cleaning.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



