project:
  type: website
  output-dir: docs


website:
  title: "MLS Team Roster Profiles"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01-01-clean-roster.qmd
      - 01-02-clean-other.qmd
      - 02-join.qmd
      - 03-quality.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged



