---
title: "MLS Player Rosters"
author: "Christian McDonald"
---

I found out from the Austin Chronicle's [Eric Goodman](https://x.com/Goodman/status/1786068099470446775) that MLS published roster information [for all MLS players](https://mlssoccer.app.box.com/s/e8eu9jpgtk09j03ynasb6zpd6hur37yk).

I downloaded the rosters in hopes of extracting the data. I cleaned it up and the files are available as CSVs below. [The code is here](https://github.com/utdata/mls-roster-profiles/).

As of May 3, 2024 this is a second pass and it still could use some Quality Checks. I've looked over `rosters` pretty well. The `others` file hasn't had as much scrutiny. If you see any problems add an issue in Github or ping me on X/Twitter [@crit](https://twitter.com/crit).

**FOR INSTANCE:** At first I was missing some teams in the "others" file because of some Pinpoint issues, but I _think_ I have fixed them.

## Published files

- [rosters.csv](data-out/rosters.csv) include the senior, supplemental and off-roster player listings for each team.
- [others.csv](data-out/others.csv) include the international slots, designated players, U22 players and unavailable players. This also includes "Notes" designations as outlined below.

I do aim to combine these two files in a meaningful way.

### Roster notes

- `notes_young` (Young DP) Indicates a Young Designated Player. (This wasn't really explained on the profiles).
- `notes_unavail` *Indicates player is currently unavailable, and club may receive roster/international spot relief, but not Salary Budget relief unless otherwise determined pursuant to the loan agreement.
- `notes_notam` ^Player cannot be converted from a Designated Player to a non-Designated Player by using Targeted Allocation Money.
- `notes_can` +In addition to the International Roster Slots, each Canadian Club is permitted to designate up to three International Players who have been under contract with MLS and registered with one or more Canadian clubs for at least one year who will not count toward the club’s International Roster Slots.
- Off-roster Homegrown players can appear in MLS matches via a Short-Term Agreement.

## How this was done

### Pinpoint extract 

I thought Google Pinpoint might be the easiest way to extract the data. Pinpoint wants individual files instead of one file with a bunch of pages, so I split the single document into individual ones for each team. I used the "table" processing to create two raw csv files:

- `data-raw/pinpoint/Rosters.csv` has the main roster that is on the left side of the page.
- `data-raw/pinpoint/Other.csv` has all the other player designations listed on the right side of the page.

In the case of this "other" data I had to do more than one pass with Pinpoint to catch all the teams so there are multiple "raw" files. They are all in [the repo](https://github.com/utdata/mls-roster-profiles/) in the data-raw folder.

I had to do combine some of those raw files to get what I hope is a full set of everything.

### Cleaning

All other cleaning was done in R in Quarto notebooks:

- [Cleaning Roster](01-cleaning-roster.qmd)
- [Cleaning Other](01-cleaning-other.qmd)

The cleaned csv files are exported into the `data-out/` folder in [the repo](https://github.com/utdata/mls-roster-profiles/). There are also some .rds files in `data-processed/`
